### ISSUE TITLE
التوثيق مترجم بالفعل

### ISSUE THREAD

**Issue by aeymash** [Syrian-Open-Source/arabic-laravel-docs#102]
مرحبًا جميعًا،

توثيق لارافل مترجم بالفعل في موسوعة حسوب:
https://wiki.hsoub.com/Laravel
الإصدار المنشور هو 5.7، ما أقترحه هو تحديث التوثيق إلى الإصدار التاسع من لارافل، منعًا لتشتيت الجهود.

يمكنكم التواصل معي لأي تفاصيل إضافية.

بالتوفيق.

**Comment by abdussalam-alali** [comment]
Thanks, @aeymash  for your suggestion,
We're already working on the latest version of laravel docs "laravel 9.x", we've seen the attached link by Hsoub it's very good work but unfortunately, it's kinda outdated.

For that reason, we're working now on translating the latest version of laravel docs.
